name: download test

on:
  workflow_dispatch:
    inputs:
      
      test:
        description: 'test'
        required: false
        default: 'test'
      
      download_artifact:
        description: 'download previous run artifact (yes/no)'
        required: true
        default: 'no'

jobs:
  download-test:
    runs-on: ubuntu-latest 
    permissions:
      issues: write 
    steps:
      - name: Download Workflow Artifcts
        run: |
          curl \
          --url https://api.github.com/repos/${{ github.repository }}/actions/artifacts/201371766/zip \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header "Accept: application/vnd.github.v3+json" \
          --output test.zip
          
      - name: list files
        run: ls -la
